REM INSERTING into EXPORT_TABLE
SET DEFINE OFF;
Insert into EXPORT_TABLE (TIMESTAMP,DB_USER,OS_USER,OBJECT_SCHEMA,OBJECT_NAME,SQL_TEXT) values (to_date('24-MAY-17','DD-MON-RR'),'TESTUSER2','oracle','TESTUSER2','T_1','select * from T_1');
Insert into EXPORT_TABLE (TIMESTAMP,DB_USER,OS_USER,OBJECT_SCHEMA,OBJECT_NAME,SQL_TEXT) values (to_date('24-MAY-17','DD-MON-RR'),'TESTUSER2','oracle','TESTUSER2','T_1','select * from T_1');
Insert into EXPORT_TABLE (TIMESTAMP,DB_USER,OS_USER,OBJECT_SCHEMA,OBJECT_NAME,SQL_TEXT) values (to_date('24-MAY-17','DD-MON-RR'),'TESTUSER2','oracle','TESTUSER2','T_1','select * from T_1');
Insert into EXPORT_TABLE (TIMESTAMP,DB_USER,OS_USER,OBJECT_SCHEMA,OBJECT_NAME,SQL_TEXT) values (to_date('24-MAY-17','DD-MON-RR'),'TESTUSER2','oracle','TESTUSER2','T_1','select * from T_1');
